
# Configuración de Logging para Lucy AI
version: 1
disable_existing_loggers: False

formatters:
  standard:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  
  detailed:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(module)s - %(funcName)s:%(lineno)d - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  
  simple:
    format: '%(levelname)s - %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout

  file_handler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: logs/lucy.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8

  error_handler:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: detailed
    filename: logs/lucy_errors.log
    maxBytes: 10485760  # 10MB
    backupCount: 3
    encoding: utf8

loggers:
  core:
    level: DEBUG
    handlers: [console, file_handler, error_handler]
    propagate: no
  
  core.lucy_ai:
    level: DEBUG
    handlers: [file_handler]
    propagate: yes
  
  core.training:
    level: INFO
    handlers: [console, file_handler]
    propagate: no
  
  tensorflow:
    level: ERROR
    handlers: [error_handler]
    propagate: no
  
  keras:
    level: ERROR
    handlers: [error_handler]
    propagate: no

root:
  level: INFO
  handlers: [console, file_handler]